### ISSUE TITLE
TypeError: Ho.BufferGeometry 

### ISSUE THREAD

**Issue by caoweirong** [vasturiano/three-conic-polygon-geometry#10]
three-conic-polygon-geometry.min.js:2 Uncaught 
TypeError: Ho.BufferGeometry is not a constructor
    at three-conic-polygon-…etry.min.js:2:84809
    at three-conic-polygon-…ometry.min.js:2:165
    at three-conic-polygon-…ometry.min.js:2:248
﻿

**Comment by vasturiano** [comment]
@caoweirong can you provide a simple reproducible example on [codepen](https://codepen.io/)?
